spring.application.name=aiproject

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=openai/gpt-4.1-nano
spring.ai.openai.chat.base-url=https://models.github.ai/inference
spring.ai.openai.chat.completions-path=/chat/completions