# Generated by Django 6.0 on 2025-12-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_encrypted', models.BooleanField(default=True)),
                ('emotion', models.CharField(blank=True, choices=[('happy', '행복'), ('sad', '슬픔'), ('angry', '화남'), ('anxious', '불안'), ('peaceful', '평온'), ('excited', '신남'), ('tired', '피곤'), ('love', '사랑')], max_length=20, null=True, verbose_name='감정')),
                ('emotion_score', models.IntegerField(blank=True, help_text='0-100 사이의 값', null=True, verbose_name='감정 강도')),
                ('emotion_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='감정 분석 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일기',
                'verbose_name_plural': '일기들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('ai_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diary.diary')),
            ],
        ),
    ]
